### ISSUE TITLE
Review labelling and signposting (final)

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_group#269]
## Additional fields added to content types in Microsites (eg page, events, news, directories etc)

- [x] Review the use of the stand first field.
- [x] Wrap banner and standfirst (if keeping) in fieldset
- [x] Rename "Content" field to "Layouts and Rich content"

## Microsite Site design fields
From ( https://github.com/localgovdrupal/localgov_microsites_group/issues/246 ) 
- [x] Put colour pairs in fieldsets to encourage people to set both
- [x] Make sure all colour fields have the colour picker
- [x] Update all help text

## Remove / update tours

Review all the current Tours. Update or remove as appropriate.

## General 

- [ ] Group invitation titles - https://github.com/localgovdrupal/localgov_microsites/issues/269 
- [ ] Primary / Secondary banner naming - https://github.com/localgovdrupal/localgov_microsites/issues/261 
- [ ] IA block naming - https://github.com/localgovdrupal/localgov_microsites_group/issues/60

**Comment by msayoung** [comment]
- [ ] Update page_section colour labels to be Primary colour and Secondary colour. (instead of Accent

**Comment by msayoung** [comment]
https://github.com/localgovdrupal/localgov_microsites_group/pull/346

**Comment by msayoung** [comment]
Merged in, the others have their own issues
